---
- name: Deploy Tanium agent on Linux endpoints
  hosts: all
  gather_facts: true
  gather_subset:
    - os_family
  vars_files:
    - deploy_config.yml

  tasks:
    - name: Set value of OS family to Linux
      set_fact:
        os_family: "Linux"
      when:
        - "ansible_facts.distribution == 'CentOS' or ansible_facts.distribution == 'RedHat'"

    - name: Set value of OS family to Windows
      set_fact:
        os_family: "Windows"
      when:
        - "ansible_facts.os_family == 'Windows'"

    - name: Set value of OS family to MacOS
      set_fact:
        os_family: "MacOSX"
      when:
        - "ansible_facts.distribution == 'MacOSX'"
  
    - name: Set value for temporary folder (Linux/Mac)
      set_fact:
        dst_temp_directory: "{{ dst_linux_temp_directory }}"
      when:
        - "os_family == 'Linux' or os_family == 'MacOSX'"

    - name: Set value for temporary folder (Windows)
      set_fact:
        dst_temp_directory: "{{ dst_win_temp_directory }}"
      when:
        - "os_family == 'Windows'"

    - name: Set value for install package (Linux)
      set_fact:
        tanium_install_package: "{{ tanium_linux_package }}"
      when:
        - "os_family == 'Linux'"

    - name: Set value for install package (Windows)
      set_fact:
        tanium_install_package: "{{ tanium_win_package }}"
      when:
        - "os_family == 'Windows'"
        
    - name: Set value for install package (MacOS)
      set_fact:
        tanium_install_package: "{{ tanium_mac_package }}"
      when:
        - "os_family == 'MacOSX'"

    - name: Create endpoint temporary directory
      ansible.builtin.file:
        path: {{ dst_temp_directory }}
        state: directory

    - name: Copy and unzip Tanium agent rpm to endpoint
      ansible.builtin.unarchive:
        src: ./{{ tanium_install_package }}
        dest: {{ dst_temp_directory }}

    # This step is not required if using TaaS, as install.sh is already part of the .zip file
    - name: Copy Linux install script to endpoint
      ansible.builtin.copy:
        src: ./install.sh
        dest: {{ dst_linux_temp_directory }}/install.sh
      when:
        - "is_taas == 'false'"

    - name: Change mode of install.sh file
      ansible.builtin.file:
        path: {{ dst_linux_temp_directory }}/install.sh
        mode: 0744

    - name: Permit traffic in default zone on port 17472/tcp
      ansible.posix.firewalld:
        port: 17472/tcp
        permanent: yes
        state: enabled

    - name: Permit traffic in default zone on port 17486/tcp if using TaaS
      ansible.posix.firewalld:
        port: 17486/tcp
        permanent: yes
        state: enabled
      when:
        - "is_taas == 'true'"

    - name: Execute install.sh shell
      ansible.builtin.shell: {{ dst_temp_directory }}/install.sh
      args:
        chdir: {{ dst_linux_temp_directory }}

