dst_linux_temp_directory: /tmp/Tanium          # Directory on endpoint where the Tanium client rpm will be copied to
dst_win_temp_directory: C:\Temp\Tanium         # Directory on endpoint where the Tanium client install will be copied to

tanium_linux_package: linux-client-bundle.zip  # Name of Linux install package
tanium_win_package: win-client-bundle.zip      # Name of Windows install package
tanium_mac_package: mac-client-bundle.zip      # Name of Mac install package

is_taas: true                                  # Is this TaaS or on-prem. Mostly used for TSE testing purposes

firewall_ports_inbound:                        # Allow inbound client traffic
  - 17472                                      # --> Tanium Core service (required for: all Tanium services)
  - 17473                                      # --> Tanium Client Container service (required for: Tanium Core Containers)
  
firewall_ports_outbound:                       # Allow outbound client traffic
  - 17472                                      # --> Tanium Core service (required for: all Tanium services)
  - 17486                                      # --> Tanium Core service (required for: TaaS service)
  - 17475                                      # --> Direct Connect (required for: Threat Response)
  - 443                                        # --> Threat Response data collection - S3 (required for: Threat Response)
  - 22                                         # --> Threat Response data collection - SFTP/SCP (required for: Threat Response)
  - 445                                        # --> Threat Response data collection - SMB (required for: Threat Response)
